### ISSUE TITLE
Home Assistance integratie

### ISSUE THREAD

**Issue by Rwill03** [vives-project-xp/Meerlagen-eb-en-vloedkar#46]
De kar moet gemonitord kunnen worden door de home assistance app, daar is er een aparte groep voor.

**Comment by Rwill03** [comment]
Na overleg met de groep voor Home Assistance, zetten we dit even op "hold", want hun code/library is nog niet gereed voor gebruik.

**Comment by Rwill03** [comment]
De Home Assistance groep heeft een template bezorgd, deze zal nu geïntegreerd worden in de code.

**Comment by JonasTBUP** [comment]
De Home Assistance groep krijgt de data binnen.
